### ISSUE TITLE
Letter casing

### ISSUE THREAD

**Issue by Ildarik** [nutboltu/react-search-field#16]
I think before searching both need to be converted to lowercase - search word and data collection.
![Screenshot from 2020-02-20 08-54-56](https://user-images.githubusercontent.com/10713674/74905235-b7c11f00-53be-11ea-99a6-7cc261c8c103.png)
![Screenshot from 2020-02-20 08-55-04](https://user-images.githubusercontent.com/10713674/74905237-babc0f80-53be-11ea-9c28-4a9855d31e5d.png)

**Comment by nutboltu** [comment]
@Ildarik That's a good point. I'll raise a PR and fix it soon

**Comment by nutboltu** [comment]
@Ildarik This functionality is in docs only. So I made the changes without version bump.
