### ISSUE TITLE
window not defined

### ISSUE THREAD

**Issue by MorpheusFT** [nutboltu/react-search-field#22]
ReferenceError: window is not defined
    at Object.<anonymous> (***/node_modules/react-search-field/dist/index.min.js:1:250)

So tried to implement it, but I get the error above. It might have something to do with me rendering it server side first and then using hydrate on client side. But still, this shouldn't happen.

**Comment by nutboltu** [comment]
@MorpheusFT can you please check with the latest version 1.1.0 and confirm if it fixes?

**Comment by MorpheusFT** [comment]
@nutboltu Yes, issue is solved. Thank you.
