### ISSUE TITLE
componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by essenbee2** [nutboltu/react-search-field#49]
Console shows this warning for the SearchField component:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

Looks like this will cause the component not to work in React 18.

**Comment by nutboltu** [comment]
@essenbee2 version 2.0.0 converts the class component to functional and also uses hooks. It will fix this issue.
